-- NL chrome. Fallback schema: replace `findash` with `n8n`. Admin only.
INSERT INTO `findash`.`ui_string` (`string_key`, `locale`, `text`) VALUES
('app.title', 'nl', 'FinDash'),
('lang.nl', 'nl', 'Nederlands'),
('lang.en', 'nl', 'English'),
('lang.ru', 'nl', 'Русский'),
('filter.from', 'nl', 'Van'),
('filter.to', 'nl', 'Tot'),
('filter.year', 'nl', 'Jaar'),
('filter.month', 'nl', 'Maand'),
('filter.rekening', 'nl', 'Rekening'),
('filter.hoofd', 'nl', 'Hoofdcategorie'),
('filter.sub', 'nl', 'Subcategorie'),
('filter.all', 'nl', 'Alle'),
('kpi.expenses', 'nl', 'Uitgaven'),
('kpi.income', 'nl', 'Inkomsten'),
('kpi.delta', 'nl', 'Verschil'),
('kpi.refunds', 'nl', 'Terugboekingen'),
('kpi.internal', 'nl', 'Interne stromen'),
('kpi.saving', 'nl', 'Sparen'),
('kpi.saving_in', 'nl', 'Sparen'),
('kpi.saving_out', 'nl', 'Opname spaarrekening'),
('kpi.saving_net', 'nl', 'Netto sparen'),
('kpi.cc_settlement', 'nl', 'CC-aflossing'),
('chart.monthly_stack', 'nl', 'Uitgaven per maand'),
('chart.donut', 'nl', 'Verdeling'),
('chart.in_vs_uit', 'nl', 'Inkomsten vs uitgaven'),
('chart.income_series', 'nl', 'Inkomsten'),
('chart.expense_series', 'nl', 'Uitgaven'),
('table.hoofd', 'nl', 'Hoofdcategorie'),
('table.sub', 'nl', 'Subcategorie'),
('table.amount', 'nl', 'Netto'),
('table.expense', 'nl', 'Uitgaven'),
('table.refund', 'nl', 'Terugboekingen'),
('table.empty', 'nl', 'Geen uitgaven in deze periode.'),
('inspect.internal', 'nl', 'Interne stromen'),
('inspect.saving', 'nl', 'Sparen'),
('inspect.col.from', 'nl', 'Van'),
('inspect.col.to', 'nl', 'Naar'),
('inspect.unknown', 'nl', 'onbekend'),
('inspect.col.desc', 'nl', 'Omschrijving'),
('inspect.col.src', 'nl', 'Bron'),
('tx.title', 'nl', 'Transacties'),
('tx.empty', 'nl', 'Geen transacties in deze selectie.'),
('tx.truncated', 'nl', 'Eerste 200 rijen. Verfijn de filters om verder te zoeken.'),
('tx.open', 'nl', 'Toon transacties'),
('tx.close', 'nl', 'Sluiten'),
('info.expenses', 'nl', 'Netto uitgaven in deze periode: afboekingen min terugboekingen. Het gemiddelde is dat bedrag gedeeld door het aantal maanden in beeld. Interne overboekingen, sparen en creditcard-aflossing tellen niet mee.'),
('info.income', 'nl', 'Echte inkomsten zoals salaris, toeslagen en belastingteruggaaf. Opnames van de spaarrekening en interne overboekingen zitten hier niet in. Het gemiddelde is over dezelfde maanden.'),
('info.delta', 'nl', 'Inkomsten minus netto uitgaven over dezelfde periode. Positief betekent dat er meer binnenkwam dan er netto is uitgegeven.'),
('info.saving_in', 'nl', 'Stortingen naar spaar (subcategorie sparen) vanaf de lopende rekening.'),
('info.saving_out', 'nl', 'Opnames vanaf de spaarrekening terug naar de lopende rekening.'),
('info.saving_net', 'nl', 'Stortingen minus opnames. Positief betekent dat er per saldo meer is gespaard dan opgenomen.'),
('tx.src.bank', 'nl', 'Bank'),
('tx.src.cc', 'nl', 'Kaart'),
('tx.kind.spend', 'nl', 'Uitgaven'),
('tx.kind.saving', 'nl', 'Sparen'),
('tx.kind.internal', 'nl', 'Interne stromen'),
('tx.kind.income', 'nl', 'Inkomsten'),
('table.income', 'nl', 'Inkomsten'),
('inspect.cc', 'nl', 'Creditcard-aflossing'),
('inspect.refunds', 'nl', 'Terugboekingen'),
('inspect.cc.matched', 'nl', 'Gekoppeld'),
('inspect.cc.unmatched_topup', 'nl', 'Extra storting'),
('inspect.cc.unmatched_cc', 'nl', 'CC zonder bank'),
('inspect.col.date', 'nl', 'Datum'),
('inspect.col.amount', 'nl', 'Bedrag'),
('inspect.col.rekening', 'nl', 'Rekening'),
('inspect.col.af_bij', 'nl', 'Af/Bij'),
('inspect.col.hoofd', 'nl', 'Hoofd'),
('inspect.col.sub', 'nl', 'Sub'),
('inspect.col.type', 'nl', 'Type'),
('inspect.col.status', 'nl', 'Status'),
('inspect.col.count', 'nl', 'Aantal'),
('footer.queries', 'nl', 'Querytijd'),
('footer.index_hint', 'nl', 'Queries > 300 ms. Overweeg een samengestelde index op (Jaar, Maand) en langere prefix op Hoofdcategorie/Subcategorie.'),
('empty.no_data', 'nl', 'Nog geen transacties.'),
('health.db_down', 'nl', 'Database niet bereikbaar.'),
('filter.clear', 'nl', 'Alle categorieën'),
('chart.monthly_stack_cat', 'nl', 'Verloop in de tijd'),
('chart.click_hint', 'nl', 'Klik op een categorie (tabel of grafiek) om het verloop te zien.'),
('zoom.now', 'nl', 'Nu in beeld'),
('kpi.avg_month', 'nl', 'gem. per maand'),
('preset.this_year', 'nl', 'Dit jaar'),
('preset.this_quarter', 'nl', 'Dit kwartaal'),
('preset.last_quarter', 'nl', 'Vorig kwartaal'),
('preset.this_month', 'nl', 'Deze maand'),
('preset.last_month', 'nl', 'Vorige maand')
ON DUPLICATE KEY UPDATE `text` = VALUES(`text`);
