-- EN/RU chrome + FinBot terms. Run after 001 and 002.
INSERT INTO `findash`.`ui_string` (`string_key`, `locale`, `text`) VALUES
('app.title', 'en', 'FinDash'),
('lang.nl', 'en', 'Nederlands'),
('lang.en', 'en', 'English'),
('lang.ru', 'en', 'Русский'),
('filter.from', 'en', 'From'),
('filter.to', 'en', 'To'),
('filter.year', 'en', 'Year'),
('filter.month', 'en', 'Month'),
('filter.rekening', 'en', 'Account'),
('filter.hoofd', 'en', 'Category'),
('filter.sub', 'en', 'Subcategory'),
('filter.all', 'en', 'All'),
('kpi.expenses', 'en', 'Spending'),
('kpi.income', 'en', 'Income'),
('kpi.delta', 'en', 'Balance'),
('kpi.refunds', 'en', 'Refunds'),
('kpi.internal', 'en', 'Internal transfers'),
('kpi.saving', 'en', 'Saving'),
('kpi.saving_in', 'en', 'Saving'),
('kpi.saving_out', 'en', 'Savings withdrawal'),
('kpi.saving_net', 'en', 'Net saving'),
('kpi.cc_settlement', 'en', 'Card repayment'),
('chart.monthly_stack', 'en', 'Spending by month'),
('chart.donut', 'en', 'Split'),
('chart.in_vs_uit', 'en', 'Income vs spending'),
('chart.income_series', 'en', 'Income'),
('chart.expense_series', 'en', 'Spending'),
('table.hoofd', 'en', 'Category'),
('table.sub', 'en', 'Subcategory'),
('table.amount', 'en', 'Net'),
('table.expense', 'en', 'Spending'),
('table.refund', 'en', 'Refunds'),
('table.empty', 'en', 'No spending in this period.'),
('inspect.internal', 'en', 'Internal transfers'),
('inspect.saving', 'en', 'Saving'),
('inspect.col.from', 'en', 'From'),
('inspect.col.to', 'en', 'To'),
('inspect.unknown', 'en', 'unknown'),
('inspect.col.desc', 'en', 'Description'),
('inspect.col.src', 'en', 'Source'),
('tx.title', 'en', 'Transactions'),
('tx.empty', 'en', 'No transactions in this selection.'),
('tx.truncated', 'en', 'First 200 rows. Narrow the filters to see more.'),
('tx.open', 'en', 'Show transactions'),
('tx.close', 'en', 'Close'),
('info.expenses', 'en', 'Net spending in this period: outgoing minus refunds. The average divides that amount by the number of months in view. Internal transfers, saving and card repayment are excluded.'),
('info.income', 'en', 'Real income such as salary, allowances and tax refunds. Savings withdrawals and internal transfers are excluded. The average uses the same months.'),
('info.delta', 'en', 'Income minus net spending over the same period. Positive means more came in than was spent.'),
('info.saving_in', 'en', 'Deposits to savings (subcategory sparen) from the current account.'),
('info.saving_out', 'en', 'Withdrawals from the savings account back to the current account.'),
('info.saving_net', 'en', 'Deposits minus withdrawals. Positive means more was saved than withdrawn.'),
('tx.src.bank', 'en', 'Bank'),
('tx.src.cc', 'en', 'Card'),
('tx.kind.spend', 'en', 'Spending'),
('tx.kind.saving', 'en', 'Saving'),
('tx.kind.internal', 'en', 'Internal transfers'),
('tx.kind.income', 'en', 'Income'),
('table.income', 'en', 'Income'),
('inspect.cc', 'en', 'Card repayment'),
('inspect.refunds', 'en', 'Refunds'),
('inspect.cc.matched', 'en', 'Matched'),
('inspect.cc.unmatched_topup', 'en', 'Extra top-up'),
('inspect.cc.unmatched_cc', 'en', 'Card without bank'),
('inspect.col.date', 'en', 'Date'),
('inspect.col.amount', 'en', 'Amount'),
('inspect.col.rekening', 'en', 'Account'),
('inspect.col.af_bij', 'en', 'Out/In'),
('inspect.col.hoofd', 'en', 'Category'),
('inspect.col.sub', 'en', 'Sub'),
('inspect.col.type', 'en', 'Type'),
('inspect.col.status', 'en', 'Status'),
('inspect.col.count', 'en', 'Count'),
('footer.queries', 'en', 'Query time'),
('footer.index_hint', 'en', 'Queries > 300 ms. Consider a composite index on (Jaar, Maand) and a longer prefix on Hoofdcategorie/Subcategorie.'),
('empty.no_data', 'en', 'No transactions yet.'),
('health.db_down', 'en', 'Database unavailable.'),
('filter.clear', 'en', 'All categories'),
('chart.monthly_stack_cat', 'en', 'Over time'),
('chart.click_hint', 'en', 'Click a category to see it over time.'),
('zoom.now', 'en', 'Now showing'),
('kpi.avg_month', 'en', 'avg. per month'),
('preset.this_year', 'en', 'This year'),
('preset.this_quarter', 'en', 'This quarter'),
('preset.last_quarter', 'en', 'Last quarter'),
('preset.this_month', 'en', 'This month'),
('preset.last_month', 'en', 'Last month'),
('app.title', 'ru', 'FinDash'),
('lang.nl', 'ru', 'Nederlands'),
('lang.en', 'ru', 'English'),
('lang.ru', 'ru', 'Русский'),
('filter.from', 'ru', 'С'),
('filter.to', 'ru', 'По'),
('filter.year', 'ru', 'Год'),
('filter.month', 'ru', 'Месяц'),
('filter.rekening', 'ru', 'Счёт'),
('filter.hoofd', 'ru', 'Категория'),
('filter.sub', 'ru', 'Подкатегория'),
('filter.all', 'ru', 'Все'),
('kpi.expenses', 'ru', 'Расходы'),
('kpi.income', 'ru', 'Доходы'),
('kpi.delta', 'ru', 'Разница'),
('kpi.refunds', 'ru', 'Возвраты'),
('kpi.internal', 'ru', 'Внутренние переводы'),
('kpi.saving', 'ru', 'Накопления'),
('kpi.saving_in', 'ru', 'Накопления'),
('kpi.saving_out', 'ru', 'Снятие со сбережений'),
('kpi.saving_net', 'ru', 'Итого накопления'),
('kpi.cc_settlement', 'ru', 'Погашение карты'),
('chart.monthly_stack', 'ru', 'Расходы по месяцам'),
('chart.donut', 'ru', 'Доли'),
('chart.in_vs_uit', 'ru', 'Доходы и расходы'),
('chart.income_series', 'ru', 'Доходы'),
('chart.expense_series', 'ru', 'Расходы'),
('table.hoofd', 'ru', 'Категория'),
('table.sub', 'ru', 'Подкатегория'),
('table.amount', 'ru', 'Итого'),
('table.expense', 'ru', 'Расходы'),
('table.refund', 'ru', 'Возвраты'),
('table.empty', 'ru', 'Нет расходов за период.'),
('inspect.internal', 'ru', 'Внутренние переводы'),
('inspect.saving', 'ru', 'Накопления'),
('inspect.col.from', 'ru', 'Откуда'),
('inspect.col.to', 'ru', 'Куда'),
('inspect.unknown', 'ru', 'неизвестно'),
('inspect.col.desc', 'ru', 'Описание'),
('inspect.col.src', 'ru', 'Источник'),
('tx.title', 'ru', 'Операции'),
('tx.empty', 'ru', 'Нет операций в этой выборке.'),
('tx.truncated', 'ru', 'Первые 200 строк. Сузьте фильтры, чтобы увидеть больше.'),
('tx.open', 'ru', 'Показать операции'),
('tx.close', 'ru', 'Закрыть'),
('info.expenses', 'ru', 'Чистые расходы за период: списания минус возвраты. Среднее — эта сумма, делённая на число месяцев на экране. Внутренние переводы, накопления и погашение карты не входят.'),
('info.income', 'ru', 'Реальные доходы: зарплата, пособия, налоговый возврат. Снятия со сбережений и внутренние переводы не входят. Среднее считается по тем же месяцам.'),
('info.delta', 'ru', 'Доходы минус чистые расходы за тот же период. Плюс означает, что пришло больше, чем потрачено.'),
('info.saving_in', 'ru', 'Пополнения сбережений (подкатегория sparen) с текущего счёта.'),
('info.saving_out', 'ru', 'Снятия со сберегательного счёта обратно на текущий.'),
('info.saving_net', 'ru', 'Пополнения минус снятия. Плюс означает, что в сумме отложено больше, чем снято.'),
('tx.src.bank', 'ru', 'Банк'),
('tx.src.cc', 'ru', 'Карта'),
('tx.kind.spend', 'ru', 'Расходы'),
('tx.kind.saving', 'ru', 'Накопления'),
('tx.kind.internal', 'ru', 'Внутренние переводы'),
('tx.kind.income', 'ru', 'Доходы'),
('table.income', 'ru', 'Доходы'),
('inspect.cc', 'ru', 'Погашение карты'),
('inspect.refunds', 'ru', 'Возвраты'),
('inspect.cc.matched', 'ru', 'Сопоставлено'),
('inspect.cc.unmatched_topup', 'ru', 'Дополнительное пополнение'),
('inspect.cc.unmatched_cc', 'ru', 'Карта без банка'),
('inspect.col.date', 'ru', 'Дата'),
('inspect.col.amount', 'ru', 'Сумма'),
('inspect.col.rekening', 'ru', 'Счёт'),
('inspect.col.af_bij', 'ru', 'Расход/приход'),
('inspect.col.hoofd', 'ru', 'Категория'),
('inspect.col.sub', 'ru', 'Подк.'),
('inspect.col.type', 'ru', 'Тип'),
('inspect.col.status', 'ru', 'Статус'),
('inspect.col.count', 'ru', 'Число'),
('footer.queries', 'ru', 'Время запросов'),
('footer.index_hint', 'ru', 'Запросы > 300 мс. Имеет смысл составной индекс на (Jaar, Maand) и более длинный префикс на Hoofdcategorie/Subcategorie.'),
('empty.no_data', 'ru', 'Пока нет операций.'),
('health.db_down', 'ru', 'База данных недоступна.'),
('filter.clear', 'ru', 'Все категории'),
('chart.monthly_stack_cat', 'ru', 'Динамика'),
('chart.click_hint', 'ru', 'Нажмите категорию, чтобы увидеть динамику.'),
('zoom.now', 'ru', 'Сейчас'),
('kpi.avg_month', 'ru', 'в среднем за месяц'),
('preset.this_year', 'ru', 'Этот год'),
('preset.this_quarter', 'ru', 'Этот квартал'),
('preset.last_quarter', 'ru', 'Прошлый квартал'),
('preset.this_month', 'ru', 'Этот месяц'),
('preset.last_month', 'ru', 'Прошлый месяц')
ON DUPLICATE KEY UPDATE `text` = VALUES(`text`);

INSERT INTO `findash`.`term` (`namespace`, `source_nl`, `locale`, `text`) VALUES
('hoofd', 'Aflossing', 'en', 'Repayment'),
('hoofd', 'Aflossing', 'ru', 'Погашение'),
('hoofd', 'Educatie', 'en', 'Education'),
('hoofd', 'Educatie', 'ru', 'Образование'),
('hoofd', 'Huishouden', 'en', 'Household'),
('hoofd', 'Huishouden', 'ru', 'Быт'),
('hoofd', 'Inkomsten', 'en', 'Income'),
('hoofd', 'Inkomsten', 'ru', 'Доходы'),
('hoofd', 'Interne overboeking', 'en', 'Internal transfer'),
('hoofd', 'Interne overboeking', 'ru', 'Внутренний перевод'),
('hoofd', 'Medische kosten', 'en', 'Medical'),
('hoofd', 'Medische kosten', 'ru', 'Медицина'),
('hoofd', 'Overige uitgaven', 'en', 'Other spending'),
('hoofd', 'Overige uitgaven', 'ru', 'Прочие расходы'),
('hoofd', 'Telecom/tech', 'en', 'Telecom/tech'),
('hoofd', 'Telecom/tech', 'ru', 'Связь и техника'),
('hoofd', 'Vervoer', 'en', 'Transport'),
('hoofd', 'Vervoer', 'ru', 'Транспорт'),
('hoofd', 'Verzekeringen', 'en', 'Insurance'),
('hoofd', 'Verzekeringen', 'ru', 'Страховки'),
('hoofd', 'Voorkomen', 'en', 'Personal care'),
('hoofd', 'Voorkomen', 'ru', 'Уход'),
('hoofd', 'Vrije tijd', 'en', 'Leisure'),
('hoofd', 'Vrije tijd', 'ru', 'Досуг'),
('hoofd', 'Wonen', 'en', 'Housing'),
('hoofd', 'Wonen', 'ru', 'Жильё'),
('sub', 'AI', 'en', 'AI'),
('sub', 'AI', 'ru', 'ИИ'),
('sub', 'WA', 'en', 'third-party insurance'),
('sub', 'WA', 'ru', 'автогражданка'),
('sub', 'abonnementen', 'en', 'subscriptions'),
('sub', 'abonnementen', 'ru', 'подписки'),
('sub', 'autoverzekering', 'en', 'car insurance'),
('sub', 'autoverzekering', 'ru', 'автостраховка'),
('sub', 'bankkosten', 'en', 'bank fees'),
('sub', 'bankkosten', 'ru', 'банковские сборы'),
('sub', 'belastingen overig', 'en', 'other taxes'),
('sub', 'belastingen overig', 'ru', 'прочие налоги'),
('sub', 'belastingteruggaaf', 'en', 'tax refund'),
('sub', 'belastingteruggaaf', 'ru', 'налоговый возврат'),
('sub', 'bibliotheek', 'en', 'library'),
('sub', 'bibliotheek', 'ru', 'библиотека'),
('sub', 'bijdrage kado', 'en', 'gift contribution'),
('sub', 'bijdrage kado', 'ru', 'вклад на подарок'),
('sub', 'bijdrage opa', 'en', 'grandpa''s contribution'),
('sub', 'bijdrage opa', 'ru', 'вклад дедушки'),
('sub', 'boeken', 'en', 'books'),
('sub', 'boeken', 'ru', 'книги'),
('sub', 'boodschappen', 'en', 'groceries'),
('sub', 'boodschappen', 'ru', 'продукты'),
('sub', 'creditcard', 'en', 'credit card'),
('sub', 'creditcard', 'ru', 'кредитная карта'),
('sub', 'crypto verkoop', 'en', 'crypto sale'),
('sub', 'crypto verkoop', 'ru', 'продажа крипты'),
('sub', 'cursus', 'en', 'course'),
('sub', 'cursus', 'ru', 'курс'),
('sub', 'dansles', 'en', 'dance class'),
('sub', 'dansles', 'ru', 'танцы'),
('sub', 'debitrente', 'en', 'debit interest'),
('sub', 'debitrente', 'ru', 'проценты по дебету'),
('sub', 'eigen bijdrage', 'en', 'copay'),
('sub', 'eigen bijdrage', 'ru', 'соплата'),
('sub', 'eigen risico', 'en', 'excess'),
('sub', 'eigen risico', 'ru', 'франшиза'),
('sub', 'elektriciteit', 'en', 'electricity'),
('sub', 'elektriciteit', 'ru', 'электричество'),
('sub', 'entertainment', 'en', 'entertainment'),
('sub', 'entertainment', 'ru', 'развлечения'),
('sub', 'fiets', 'en', 'bicycle'),
('sub', 'fiets', 'ru', 'велосипед'),
('sub', 'geldopnames', 'en', 'cash withdrawals'),
('sub', 'geldopnames', 'ru', 'снятие наличных'),
('sub', 'gemeentebelasting', 'en', 'municipal tax'),
('sub', 'gemeentebelasting', 'ru', 'муниципальный налог'),
('sub', 'glazenwassers', 'en', 'window cleaners'),
('sub', 'glazenwassers', 'ru', 'мойка окон'),
('sub', 'goede doelen', 'en', 'charity'),
('sub', 'goede doelen', 'ru', 'благотворительность'),
('sub', 'hellofresh', 'en', 'HelloFresh'),
('sub', 'hellofresh', 'ru', 'HelloFresh'),
('sub', 'home automation', 'en', 'home automation'),
('sub', 'home automation', 'ru', 'умный дом'),
('sub', 'hypotheek', 'en', 'mortgage'),
('sub', 'hypotheek', 'ru', 'ипотека'),
('sub', 'iCloud', 'en', 'iCloud'),
('sub', 'iCloud', 'ru', 'iCloud'),
('sub', 'inrichting', 'en', 'furnishing'),
('sub', 'inrichting', 'ru', 'обстановка'),
('sub', 'intern', 'en', 'internal'),
('sub', 'intern', 'ru', 'внутреннее'),
('sub', 'internet', 'en', 'internet'),
('sub', 'internet', 'ru', 'интернет'),
('sub', 'kado''s', 'en', 'gifts'),
('sub', 'kado''s', 'ru', 'подарки'),
('sub', 'kapper', 'en', 'hairdresser'),
('sub', 'kapper', 'ru', 'парикмахер'),
('sub', 'katten', 'en', 'cats'),
('sub', 'katten', 'ru', 'кошки'),
('sub', 'kinderbijslag', 'en', 'child benefit'),
('sub', 'kinderbijslag', 'ru', 'детское пособие'),
('sub', 'kinderopvang', 'en', 'childcare'),
('sub', 'kinderopvang', 'ru', 'детский сад'),
('sub', 'kleding', 'en', 'clothing'),
('sub', 'kleding', 'ru', 'одежда'),
('sub', 'laadpaal', 'en', 'EV charger'),
('sub', 'laadpaal', 'ru', 'зарядка'),
('sub', 'laadvergoeding', 'en', 'charging reimbursement'),
('sub', 'laadvergoeding', 'ru', 'возмещение зарядки'),
('sub', 'lekkernijen', 'en', 'treats'),
('sub', 'lekkernijen', 'ru', 'сладости'),
('sub', 'lekker­nijen', 'en', 'treats'),
('sub', 'lekker­nijen', 'ru', 'сладости'),
('sub', 'manicure/pedicure', 'en', 'manicure/pedicure'),
('sub', 'manicure/pedicure', 'ru', 'маникюр/педикюр'),
('sub', 'mobiel', 'en', 'mobile'),
('sub', 'mobiel', 'ru', 'мобильная связь'),
('sub', 'onderhoud', 'en', 'maintenance'),
('sub', 'onderhoud', 'ru', 'обслуживание'),
('sub', 'opstal', 'en', 'buildings insurance'),
('sub', 'opstal', 'ru', 'страховка жилья'),
('sub', 'overig', 'en', 'other'),
('sub', 'overig', 'ru', 'прочее'),
('sub', 'overlijdensrisico', 'en', 'life insurance'),
('sub', 'overlijdensrisico', 'ru', 'страхование жизни'),
('sub', 'parkeren', 'en', 'parking'),
('sub', 'parkeren', 'ru', 'парковка'),
('sub', 'salaris', 'en', 'salary'),
('sub', 'salaris', 'ru', 'зарплата'),
('sub', 'school', 'en', 'school'),
('sub', 'school', 'ru', 'школа'),
('sub', 'schoonmaakster', 'en', 'cleaner'),
('sub', 'schoonmaakster', 'ru', 'уборка'),
('sub', 'schuldaflossing', 'en', 'debt repayment'),
('sub', 'schuldaflossing', 'ru', 'погашение долга'),
('sub', 'software', 'en', 'software'),
('sub', 'software', 'ru', 'ПО'),
('sub', 'sparen', 'en', 'saving'),
('sub', 'sparen', 'ru', 'накопления'),
('sub', 'sport', 'en', 'sport'),
('sub', 'sport', 'ru', 'спорт'),
('sub', 'studiefonds kinderen', 'en', 'children''s study fund'),
('sub', 'studiefonds kinderen', 'ru', 'учёба детей'),
('sub', 'supplementen', 'en', 'supplements'),
('sub', 'supplementen', 'ru', 'БАДы'),
('sub', 'taalcursus', 'en', 'language course'),
('sub', 'taalcursus', 'ru', 'языковой курс'),
('sub', 'toeslagen', 'en', 'allowances'),
('sub', 'toeslagen', 'ru', 'пособия'),
('sub', 'tol', 'en', 'toll'),
('sub', 'tol', 'ru', 'дорожный сбор'),
('sub', 'tuin', 'en', 'garden'),
('sub', 'tuin', 'ru', 'сад'),
('sub', 'uit bouwdepot', 'en', 'from building deposit'),
('sub', 'uit bouwdepot', 'ru', 'из строительного депозита'),
('sub', 'uit eten', 'en', 'eating out'),
('sub', 'uit eten', 'ru', 'рестораны'),
('sub', 'uitstapjes', 'en', 'outings'),
('sub', 'uitstapjes', 'ru', 'прогулки'),
('sub', 'uitvaart', 'en', 'funeral'),
('sub', 'uitvaart', 'ru', 'похороны'),
('sub', 'vakantie', 'en', 'holiday'),
('sub', 'vakantie', 'ru', 'отпуск'),
('sub', 'van spaarrekening', 'en', 'from savings'),
('sub', 'van spaarrekening', 'ru', 'со сбережений'),
('sub', 'verbouwing', 'en', 'renovation'),
('sub', 'verbouwing', 'ru', 'ремонт'),
('sub', 'verzorging', 'en', 'toiletries'),
('sub', 'verzorging', 'ru', 'уход'),
('sub', 'warmte', 'en', 'heat'),
('sub', 'warmte', 'ru', 'тепло'),
('sub', 'water', 'en', 'water'),
('sub', 'water', 'ru', 'вода'),
('sub', 'waterschapsbelasting', 'en', 'water board tax'),
('sub', 'waterschapsbelasting', 'ru', 'водный налог'),
('sub', 'zakgeld', 'en', 'pocket money'),
('sub', 'zakgeld', 'ru', 'карманные'),
('sub', 'zorgverzekering', 'en', 'health insurance'),
('sub', 'zorgverzekering', 'ru', 'медстраховка'),
('sub', 'zwemles', 'en', 'swimming lessons'),
('sub', 'zwemles', 'ru', 'плавание'),
('rekening', 'Oranje Spaarrekening', 'en', 'Oranje savings'),
('rekening', 'Oranje Spaarrekening', 'ru', 'Oranje'),
('rekening', 'Rekening opa', 'en', 'Grandpa'),
('rekening', 'Rekening opa', 'ru', 'Дедушка'),
('rekening', 'spaarrekening', 'en', 'savings account'),
('rekening', 'spaarrekening', 'ru', 'сбережения'),
('cc_type', 'Betaling', 'en', 'Payment'),
('cc_type', 'Betaling', 'ru', 'Платёж'),
('cc_type', 'Incasso', 'en', 'Direct debit'),
('cc_type', 'Incasso', 'ru', 'Инкассо'),
('cc_type', 'Kosten', 'en', 'Fees'),
('cc_type', 'Kosten', 'ru', 'Комиссия'),
('af_bij', 'Af', 'en', 'Out'),
('af_bij', 'Af', 'ru', 'Расход'),
('af_bij', 'Bij', 'en', 'In'),
('af_bij', 'Bij', 'ru', 'Приход')
ON DUPLICATE KEY UPDATE `text` = VALUES(`text`);
