-- Import-studio: keep original category for undo. Similarity already on copy.
-- IF NOT EXISTS: MariaDB 10.3.3+ / 11.4.

ALTER TABLE `findash`.`FinBotTransactions`
  ADD COLUMN IF NOT EXISTS `oorsprong_hoofd` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `oorsprong_sub` VARCHAR(191) NULL;

ALTER TABLE `findash`.`FinBotTransactionsCC`
  ADD COLUMN IF NOT EXISTS `oorsprong_hoofd` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `oorsprong_sub` VARCHAR(191) NULL;

INSERT INTO `findash`.`ui_string` (`string_key`, `locale`, `text`) VALUES
('studio.nav', 'nl', 'Import-studio'),
('studio.title', 'nl', 'Import-studio'),
('studio.lead', 'nl', 'Corrigeer categorieën op bestaande rijen. Bestandsimport volgt.'),
('studio.queue', 'nl', 'Wachtrij'),
('studio.queue.overig', 'nl', 'Overig'),
('studio.queue.saving_odd', 'nl', 'Sparen (geen spaarlabel)'),
('studio.queue.unclassified', 'nl', 'Ongeclassificeerd'),
('studio.queue.corrected', 'nl', 'Gecorrigeerd'),
('studio.queue.all', 'nl', 'Alle (excl. intern)'),
('studio.suggest', 'nl', 'Suggestie'),
('studio.similarity', 'nl', 'Similarity'),
('studio.save', 'nl', 'Opslaan'),
('studio.undo', 'nl', 'Ongedaan'),
('studio.neighbors', 'nl', 'Buren'),
('studio.qdrant_down', 'nl', 'Qdrant niet bereikbaar; handmatig opslaan kan wel.'),
('studio.threshold', 'nl', 'Drempel'),
('studio.empty', 'nl', 'Niets in deze wachtrij voor deze periode.'),
('studio.above', 'nl', 'boven drempel'),
('studio.file_later', 'nl', 'Bank-CSV en CC-PDF komen in een volgende stap. Nu: bestaande rijen hercategoriseren.'),
('studio.page', 'nl', 'Pagina'),
('studio.current', 'nl', 'Nu'),
('studio.nav', 'en', 'Import studio'),
('studio.title', 'en', 'Import studio'),
('studio.lead', 'en', 'Correct categories on existing rows. File import comes next.'),
('studio.queue', 'en', 'Queue'),
('studio.queue.overig', 'en', 'Other'),
('studio.queue.saving_odd', 'en', 'Saving (not a savings label)'),
('studio.queue.unclassified', 'en', 'Unclassified'),
('studio.queue.corrected', 'en', 'Corrected'),
('studio.queue.all', 'en', 'All (excl. internal)'),
('studio.suggest', 'en', 'Suggestion'),
('studio.similarity', 'en', 'Similarity'),
('studio.save', 'en', 'Save'),
('studio.undo', 'en', 'Undo'),
('studio.neighbors', 'en', 'Neighbors'),
('studio.qdrant_down', 'en', 'Qdrant is down; you can still save by hand.'),
('studio.threshold', 'en', 'Threshold'),
('studio.empty', 'en', 'Nothing in this queue for this period.'),
('studio.above', 'en', 'above threshold'),
('studio.file_later', 'en', 'Bank CSV and card PDF follow in a later step. For now: recategorise existing rows.'),
('studio.page', 'en', 'Page'),
('studio.current', 'en', 'Now'),
('studio.nav', 'ru', 'Студия импорта'),
('studio.title', 'ru', 'Студия импорта'),
('studio.lead', 'ru', 'Исправьте категории у существующих строк. Импорт файлов будет позже.'),
('studio.queue', 'ru', 'Очередь'),
('studio.queue.overig', 'ru', 'Прочее'),
('studio.queue.saving_odd', 'ru', 'Накопления (не сбережения)'),
('studio.queue.unclassified', 'ru', 'Без класса'),
('studio.queue.corrected', 'ru', 'Исправлено'),
('studio.queue.all', 'ru', 'Все (кроме внутренних)'),
('studio.suggest', 'ru', 'Подсказка'),
('studio.similarity', 'ru', 'Similarity'),
('studio.save', 'ru', 'Сохранить'),
('studio.undo', 'ru', 'Отмена'),
('studio.neighbors', 'ru', 'Соседи'),
('studio.qdrant_down', 'ru', 'Qdrant недоступен; ручное сохранение работает.'),
('studio.threshold', 'ru', 'Порог'),
('studio.empty', 'ru', 'В этой очереди за период ничего нет.'),
('studio.above', 'ru', 'выше порога'),
('studio.file_later', 'ru', 'CSV банка и PDF карты — следующим шагом. Сейчас: перекатегоризация существующих строк.'),
('studio.page', 'ru', 'Страница'),
('studio.current', 'ru', 'Сейчас')
ON DUPLICATE KEY UPDATE `text` = VALUES(`text`);
